version: '3'

services: 
  rabbit:
    restart: always
    image: 'rabbitmq:3.7.4-management'
    ports:
      - "15672:15672"
    networks:
      default:
          aliases:
            - rabbit

  store:
    restart: always
    image: eiffel-community/eiffel-store:devbuild
    build:
      context: .
      dockerfile: docker/dev.dockerfile
      args:
        INSTALL_MONGO: "false"
        INSTALL_PHANTOM_JS: "false"
        INSTALL_GRAPHICSMAGIK: "false"
    environment: 
      MONGO_URL: mongodb://mongo:27017/meteor
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    depends_on: 
      - mongo
    networks:
      default:
        aliases:
          - store
  
  mongo:
    restart: always
    image: mongo
    volumes:
      - .meteor/local/db:/data/db
    networks:
      default:
        aliases:
          - mongo

  publish:
    image: jadyoung/publish-file-to-rabbit
    environment:
      AMQP_HOST: "rabbit"
      QUEUE_NAME: "vici"
    networks:
      default:
        aliases:
          - publish
    depends_on:
      - rabbit

  plumb-rabbit-to-mongo:
    restart: always
    image: jadyoung/plumb-rabbit-to-mongo:latest
    depends_on:
      - rabbit
      - mongo
    environment:
      MONGO_URI: mongodb://mongo/meteor
      MONGO_COLLECTION: eiffel-events
      RABBIT_URI: amqp://guest:guest@rabbit:5672/
      RABBIT_QUEUE_NAME: vici
    networks:
      default:
        aliases:
          - plumb-rabbit-to-mongo
